name = "LearnJuliaTheFunWay"
uuid = "3c731e86-efac-404e-a11e-64be989f1dca"
authors = ["Jun Tian <tianjun.cpp@gmail.com>"]
version = "0.1.0"

[deps]
Books = "939d5c6b-51ae-42e7-97ca-7564d0d4ad91"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Books = "0.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]